name: Render with SimplyMarkdown

on:
  push:
    branches: 
    - source

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install markdown==3.3.4 jinja2 Pygments BeautifulSoup4
    - name: Clone SimplyMarkdown
      run: git clone https://github.com/cemreefe/SimplyMarkdown
    - name: Run SimplyMarkdown
      run: |
        cd SimplyMarkdown
        python3 render.py -i ../source -o ../output --title 'Misty Step Blog' --css ../source/static/css/style.css --root 'https://mistystep.org' --favicon 🌫️ --rss-whitelist '/blog/*'
    - name: Cleanup repo
      run: |
        rm -r SimplyMarkdown
    - name: Clone github pages branch and clean its contents
      run: |
        cd ..
        mkdir ghp
        cd ghp
        git clone -b gh-pages https://github.com/${{ github.actor }}/${{ github.event.repository.name }}
        cd ${{ github.event.repository.name }}
        # Retrieve the latest commit message from the source branch
        LATEST_COMMIT_MSG=$(git -C . log -1 --pretty=%B)
        # Delete everything from source
        git rm -r '*' 
    - name: Move new output into github pages branch
      run: |
        mv output/* ../ghp/${{ github.event.repository.name }}/
        
    - name: Commit changes
      run: |
        cd ../ghp/${{ github.event.repository.name }}/
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.AUTO_RENDER_PAT }}@github.com/$GITHUB_REPOSITORY
        git add -A 
        # Prepend SimplyMarkdown - to the commit message
        COMMIT_MSG="SimplyMarkdown - $LATEST_COMMIT_MSG"
        git commit -m "$COMMIT_MSG"
        git push
    
